remote_theme: thuhcsi/secap_slate
title: SECAP Speech Emotion Captioning with Large Language Model
description: Accepted by AAAI 2024.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
